package grupo7.volutarapp.model.enums;

public enum Servicio {
    ALIMENTOS_Y_BEBIDAS,
    MANTENIMIENTO_DEL_HOGAR,
    ASISTENCIA_PARA_PERSONAS_MAYORES,
    ROPA_Y_CALZADO,
    AYUDA_CON_EL_TRANSPORTE,
    ASISTENCIA_MEDICA,
    APOYO_EMOCIONAL,
    TUTORIA_ACADEMICA,
    CUIDADO_DE_MASCOTAS,
    ORIENTACION_LEGAL,
    ASISTENCIA_PARA_PERSONAS_CON_DISCAPACIDAD,
    SERVICIOS_DE_TRADUCCION_E_INTERPRETACION,
    ASISTENCIA_CON_TRAMITES_ADMINISTRATIVOS,
    AYUDA_CON_LA_LIMPIEZA_DEL_HOGAR,
    SUMINISTROS_BASICOS_DE_HIGIENE,
    ASESORAMIENTO_FINANCIERO,
    ENTREGA_DE_MEDICAMENTO,
    ASISTENCIA_CON_LA_TECNOLOGIA_Y_LA_INFORMATICA,
    AYUDA_PARA_LA_BUSQUEDA_DE_EMPLEO
}
